### PR TITLE
feat: mrsv

### LINKED ISSUE #23: MSRV Requirement
https://github.com/fission-codes/fission-cli/issues/19

Minimum Supported Rust Version (MSRV) to determine and maintain is usually something people look for.

Also it drives the testing requirements in the CI / pre-release.

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
minimum rust-supported version, set for 1.64, no prompt

- [X] New feature (non-breaking change that adds functionality)

Fixes #23

### CODE REVIEW

**Review by matheus23 — APPROVED** [review]
Again, I know little about these things, but looks reasonable :+1: 

One thing I wonder is whether there's a way around the minimum version to be hardcoded in multiple places. I.e. is it possible to have e.g. the workflows' toolchain version to be loaded from the `Cargo.toml`'s rust-version?

**Comment by matheus23** [comment]
In any case, this is an improvement as-is, so IMO if my suggestion makes sense it could still just be an issue + another PR :)

**Comment by pinkforest** [comment]
fwiw - I usually put them all into matrix like this maximalist: https://github.com/rinse-repeat/rust-auditable-builder

**Comment by appcypher** [comment]
What is the case against getting it from a prompt?

**Pull request merged**
